version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - api
    volumes:
      - postgres_database:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  
  

  app:
    build: .
    networks:
      - api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DB_HOST}
    depends_on:
      - postgres
      - redis

volumes:
  postgres_database:

networks:
  api:
    driver: bridge